SweetTreats/Models/Client.cs
using System.Collections.Generic;

namespace SweetTreats.Models
{
  public class Client
    {
        public Client()
        {
          this.Flavors = new HashSet<Checkout>();
        }

        public int ClientId { get; set; }
        public string ClientName { get; set; }
         public virtual ApplicationUser User { get; set; }

        public virtual ICollection<Checkout> Flavors { get; set; }
    }
}

SweetTreats/Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc;
using SweetTreats.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace SweetTreats.Controllers
{
  [Authorize]
  public class ClientsController : Controller
  {
    private readonly SweetTreatsContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public ClientsController(UserManager<ApplicationUser> userManager, SweetTreatsContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public async Task<ActionResult> Index()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userClient = _db.Clients.Where(entry => entry.User.Id == currentUser.Id);
      return View(userClient);
    }

    public ActionResult Create()
    {
      ViewBag.ClientId = new SelectList(_db.Clients, "ClientId", "ClientName");
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Client Client, int FlavorId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      Client.User = currentUser;
      _db.Clients.Add(Client);
      if (FlavorId != 0)
      {
        _db.Checkout.Add(new Checkout() { ClientId = Client.ClientId, FlavorId = FlavorId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  public ActionResult Details(int id)
    {
      var thisClient = _db.Clients
          .Include(Client => Client.Flavors)
          .ThenInclude(join => join.Flavor)
          .FirstOrDefault(Client => Client.PatronId == id);
      return View(thisPatron);
    }

    public ActionResult Edit(int id)
    {
      var thisPatron = _db.Patrons.FirstOrDefault(patrons => patrons.PatronId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View(thisPatron);
    }

    [HttpPost]
    public ActionResult Edit(Patron patron, int FlavorId)
    {
      if (FlavorId != 0)
      {
        _db.Checkout.Add(new Checkout() { FlavorId = FlavorId, PatronId = patron.PatronId });
      }
      _db.Entry(patron).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddFlavor(int id)
    {
      var thisPatron = _db.Patrons.FirstOrDefault(patrons => patrons.PatronId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View(thisPatron);
    }

    [HttpPost]
    public ActionResult AddFlavor(Flavor flavor, int FlavorId)
    {
      if (FlavorId != 0)
      {
        _db.Checkout.Add(new Checkout() { FlavorId = FlavorId, PatronId = flavor.PatronId });
        
        var thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == FlavorId);
        // thisFlavor.Quantity -=1;
        _db.Entry(thisFlavor).State = EntityState.Modified;
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisPatron = _db.Patrons.FirstOrDefault(patrons => patrons.PatronId == id);
      return View(thisPatron);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisPatron = _db.Patrons.FirstOrDefault(patrons => patrons.PatronId == id);
      _db.Patrons.Remove(thisPatron);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteFlavor(int joinId)
    {
      var joinEntry = _db.Checkout.FirstOrDefault(entry => entry.CheckoutId == joinId);
      var flavorId = joinEntry.FlavorId;
      var thisTitle = _db.Flavors.FirstOrDefault(titles => titles.FlavorId == flavorId);
      // thisTitle.Quantity +=1;
      _db.Checkout.Remove(joinEntry);
      _db.Entry(thisTitle).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

SweetTreats/Views/Clients/AddFlavor.cshtml
@{
  Layout = "_Layout";
}

@model SweetTreats.Models.Client

<h2>Add a flavor</h2>

<h4>Add a flavor to this Client for checkout: @Html.DisplayFor(model => model.ClientName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.ClientId)

    @Html.Label("Select flavor")
    @Html.DropDownList("FlavorId")

    <input type="submit" value="Buy Treat!" class="btn btn-dark"/>
}

<p class="btn btn-dark">@Html.ActionLink("Back to list", "Index")</p>

SweetTreats/Views/Clients/Create.cshtml
@{
  Layout = "_Layout";
}
@model SweetTreats.Models.Client

<h4>Add a new order for @Html.LabelFor(model => model.ClientName)</h4>
<hr />

<div class ="col-md-8 offset-md-2">
  @using (Html.BeginForm())
  {
      @Html.LabelFor(model => model.ClientName)
      @Html.TextBoxFor(model => model.ClientName, new { @class = "form-control" , required = "required"})
      <input type="submit" value="Add new Client" class="btn btn-dark" />
  }
  <br>
</div>


<br>
<p class="btn btn-dark">@Html.ActionLink("Show all Clients", "Index")</p>

SweetTreats/Views/Clients/Delete.cshtml
@{
  Layout = "_Layout";
}

@model SweetTreats.Models.Client

<h2>Are you sure you want to delete this order?</h2>

@Html.DisplayNameFor(model => model.ClientName): @Html.DisplayFor(model => model.ClientName)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" class="btn btn-dark"/>
}

SweetTreats/Views/Clients/Details.cshtml
@{
  Layout = "_Layout";
}
@model SweetTreats.Models.Client
<div class="container">
  <div class="form-header">
    <h2>Client Order Details</h2>
  </div>
  <hr />
  <div class="form-body">
    <h3>@Html.DisplayNameFor(model => model.ClientName): @Html.DisplayFor(model => model.ClientName)</h3>

    @if(@Model.Flavors.Count == 0)
    {
      <p>This Client does not have any orders currently.</p>
    }
    else
    {
      <h4>Current Order: </h4>
      <ul>
      @foreach(var join in Model.Flavors)
      {
        <li>@join.Flavor.FlavorName</li>
        @using (Html.BeginForm("DeleteFlavor", "Clients"))
        {
          @Html.Hidden("joinId", @join.CheckoutId)
          <input type="submit" value="Delete" class="btn btn-dark"/>
        }
      }
      </ul>
    }
    <div class="row">
      <div class="col-sm-12">
        <p class="btn btn-dark">@Html.ActionLink("Back to list", "Index")</p>
        <p class="btn btn-dark">@Html.ActionLink("Edit Name", "Edit", new { id = Model.ClientId })</p>
        <p class="btn btn-dark">@Html.ActionLink("Delete Client", "Delete", new { id = Model.ClientId })</p>
        <p class="btn btn-dark">@Html.ActionLink("Make Order", "AddFlavor", "Clients", new { id = Model.ClientId })</p>
      </div>
    </div>
  </div>
</div>

SweetTreats/Views/Clients/Edit.cshtml
@{
  Layout = "_Layout";
}

@model SweetTreats.Models.Client

<h2>Edit</h2>

<h4>Edit this Client: @Html.DisplayFor(model => model.ClientName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.ClientId)

    @Html.LabelFor(model => model.ClientName)
    @Html.EditorFor(model => model.ClientName)

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index", null, new { @class = "btn btn-dark btn-large" })</p>

SweetTreats/Views/Clients/Index.cshtml
@{
  Layout = "_Layout";
}

@using SweetTreats.Models;
@using System.Security.Claims
@model IEnumerable<SweetTreats.Models.Client>

<h1>Clients at our bakery: @User.Identity.Name</h1>
<hr />

@if (Model.Any())
{
  <ul>
    @foreach (Client Client in Model)
    {
      <li>@Html.ActionLink($"{Client.ClientName}", "Details", new { id = Client.ClientId })</li>
    }
  </ul>
} 
else
{
  <h3>No treats have been added your order yet!</h3>
}

<p class="btn btn-dark">@Html.ActionLink("Add new order", "Create")</p>

<p class="btn btn-dark">@Html.ActionLink("Home", "Index", "Home")</p>